### ISSUE TITLE
Bach init 17ea will deletes the local Bach jar

### ISSUE THREAD

**Issue by carldea** [sormuras/bach-init#1]
I’m not sure if this is a bug or not. 
When i do the following:
```bash
$ bach init 17ea
```
Notice above I forgot the hyphen. It sh/b 17-ea. When I hit enter it will try and find jar on github getting a 404 error. Bach will deletes the local jar. Should it do that? 
As a user(panicky), I’d do a `bach clean` and get module not found… (b/c it’s deleted).

```bash
cdea-MBP:worldclock cdea$ bach init 17ea

    528 .bach/bin/bach
    537 .bach/bin/bach.bat
 26,289 .bach/bin/boot.java
    563 .bach/bin/boot.jsh
  2,926 .bach/bin/init.java
Exception in thread "main" java.io.FileNotFoundException: https://github.com/sormuras/bach/releases/download/17ea/com.github.sormuras.bach@17ea.jar
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1981)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at java.base/java.net.URL.openStream(URL.java:1167)
        at init.copy(init.java:84)
        at init.loadModule(init.java:79)
        at init.main(init.java:30)
```

To fix the problem I basically did the following:
```bash
bach init 17-ea
```

**Comment by sormuras** [comment]
https://github.com/sormuras/bach-init/blob/934be65f64a60f9fc173c07b0e8f2e278c03ad28/init.java#L21-L25

A temporary directoy is now used to download all required files first. IFF that succeeds, the files in `.bach/bin` will be replaced.
